# values for hippo-ai helm chart
image:
  repository: "<REGISTRY_HOST>/hippo-ai/api"
  tag: "latest"
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  host: "hippo-ai.example.com"
resources: {}
postgres:
  enabled: false
redis:
  enabled: false
gpu:
  enabled: true
  nodeSelector:
    nvidia.com/gpu: "present"
