apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hippo-ai.fullname" . }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hippo-ai.name" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "hippo-ai.name" . }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["worker"]
          resources: {{ toYaml .Values.resources | nindent 10 }}
      nodeSelector: {{ toYaml .Values.gpu.nodeSelector | nindent 6 }}
      restartPolicy: Always
