apiVersion: v1
kind: Service
metadata:
  name: {{ include "hippo-ai.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "hippo-ai.name" . }}-api
